language: node_js
node_js: 8
script:
  - npm test
  - npm build
after_script: cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
# after_success:
  # - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
